#!/usr/bin/env python3
import sys
import os

# Ensure local source directory is available on path resolution
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from src.lexer import Lexer
from src.parser import Parser
from src.evaluator import Evaluator
from src.environment import Environment

def main():
    if len(sys.argv) < 2:
        print("Aura Language v0.1.0")
        print("Usage: ./aura [script.au]")
        sys.exit(1)

    script_path = sys.argv[1]
    
    if not os.path.exists(script_path):
        print(f"Error: File '{script_path}' not found.")
        sys.exit(1)

    with open(script_path, 'r') as file:
        source_code = file.read()

    # Run the full Aura compilation pipeline
    lexer = Lexer(source_code)
    parser = Parser(lexer)
    program = parser.parse_program()

    if len(parser.errors) > 0:
        print(f"❌ Syntax Error compilation aborted:")
        for err in parser.errors:
            print(f"  {err}")
        sys.exit(1)

    global_env = Environment()
    evaluator = Evaluator()
    
    # Execute the file!
    evaluator.eval(program, global_env)

if __name__ == "__main__":
    main()
